#ifndef _LOADCFG_
#define _LOADCFG_
#include <string>
using namespace std;
using graph = int;
using Tchar = const TCHAR*;

extern int CharaX;
extern int CharaY;
extern int MessageWindowX;
extern int MessageWindowY;
extern int MessageX;
extern int MessageY;

extern const char* chara;
extern const char* mswindow;

extern const char* string1;
extern const char* string2;
extern const char* string3;
extern const char* string4;
extern const char* string5;
extern const char* string6;
extern const char* string7;
extern const char* string8;
extern const char* string9;
extern const char* string10;
extern const char* string11;
extern const char* string12;
extern const char* string13;
extern const char* string14;
extern const char* string15;
extern const char* string16;
extern const char* string17;
extern const char* string18;
extern const char* string19;
extern const char* string20;
extern const char* string21;
extern const char* string22;
extern const char* string23;
extern const char* string24;
extern const char* string25;
extern const char* string26;
extern const char* string27;
extern const char* string28;
extern const char* string29;
extern const char* string30;
extern const char* string31;
extern const char* string32;
extern const char* string33;
extern const char* string34;
extern const char* string35;
extern const char* string36;
extern const char* string37;
extern const char* string38;
extern const char* string39;
extern const char* string40;
extern const char* string41;
extern const char* string42;
extern const char* string43;
extern const char* string44;
extern const char* string45;
extern const char* string46;
extern const char* string47;
extern const char* string48;
extern const char* string49;
extern const char* string50;
extern const char* string51;
extern const char* string52;
extern const char* string53;
extern const char* string54;
extern const char* string55;
extern const char* string56;
extern const char* string57;
extern const char* string58;
extern const char* string59;
extern const char* string60;
extern const char* string61;
extern const char* string62;
extern const char* string63;
extern const char* string64;
extern const char* string65;
extern const char* string66;
extern const char* string67;
extern const char* string68;
extern const char* string69;
extern const char* string70;
extern const char* string71;
extern const char* string72;
extern const char* string73;
extern const char* string74;
extern const char* string75;
extern const char* string76;
extern const char* string77;
extern const char* string78;
extern const char* string79;
extern const char* string80;
extern const char* string81;
extern const char* string82;
extern const char* string83;
extern const char* string84;
extern const char* string85;
extern const char* string86;
extern const char* string87;
extern const char* string88;
extern const char* string89;
extern const char* string90;
extern const char* string91;
extern const char* string92;
extern const char* string93;
extern const char* string94;
extern const char* string95;
extern const char* string96;
extern const char* string97;
extern const char* string98;
extern const char* string99;
extern const char* string100;

extern int string1_M;
extern int string2_M;
extern int string3_M;
extern int string4_M;
extern int string5_M;
extern int string6_M;
extern int string7_M;
extern int string8_M;
extern int string9_M;
extern int string10_M;
extern int string11_M;
extern int string12_M;
extern int string13_M;
extern int string14_M;
extern int string15_M;
extern int string16_M;
extern int string17_M;
extern int string18_M;
extern int string19_M;
extern int string20_M;
extern int string21_M;
extern int string22_M;
extern int string23_M;
extern int string24_M;
extern int string25_M;
extern int string26_M;
extern int string27_M;
extern int string28_M;
extern int string29_M;
extern int string30_M;
extern int string31_M;
extern int string32_M;
extern int string33_M;
extern int string34_M;
extern int string35_M;
extern int string36_M;
extern int string37_M;
extern int string38_M;
extern int string39_M;
extern int string40_M;
extern int string41_M;
extern int string42_M;
extern int string43_M;
extern int string44_M;
extern int string45_M;
extern int string46_M;
extern int string47_M;
extern int string48_M;
extern int string49_M;
extern int string50_M;
extern int string51_M;
extern int string52_M;
extern int string53_M;
extern int string54_M;
extern int string55_M;
extern int string56_M;
extern int string57_M;
extern int string58_M;
extern int string59_M;
extern int string60_M;
extern int string61_M;
extern int string62_M;
extern int string63_M;
extern int string64_M;
extern int string65_M;
extern int string66_M;
extern int string67_M;
extern int string68_M;
extern int string69_M;
extern int string70_M;
extern int string71_M;
extern int string72_M;
extern int string73_M;
extern int string74_M;
extern int string75_M;
extern int string76_M;
extern int string77_M;
extern int string78_M;
extern int string79_M;
extern int string80_M;
extern int string81_M;
extern int string82_M;
extern int string83_M;
extern int string84_M;
extern int string85_M;
extern int string86_M;
extern int string87_M;
extern int string88_M;
extern int string89_M;
extern int string90_M;
extern int string91_M;
extern int string92_M;
extern int string93_M;
extern int string94_M;
extern int string95_M;
extern int string96_M;
extern int string97_M;
extern int string98_M;
extern int string99_M;
extern int string100_M;

//const char* IniLoadString(string filepass, string section, string key);
template <typename Type>Type IniLoadValue(string filepass, string section, string key, Type defaultvalue);
#endif