#include "DxLib.h"
#include "LoadCfg.h"

//会話画像
TCHAR chara[64];
TCHAR mswindow[64];

TCHAR string1[64];
TCHAR string2[64];
TCHAR string3[64];
TCHAR string4[64];
TCHAR string5[64];
TCHAR string6[64];
TCHAR string7[64];
TCHAR string8[64];
TCHAR string9[64];
TCHAR string10[64];
TCHAR string11[64];
TCHAR string12[64];
TCHAR string13[64];
TCHAR string14[64];
TCHAR string15[64];
TCHAR string16[64];
TCHAR string17[64];
TCHAR string18[64];
TCHAR string19[64];
TCHAR string20[64];
TCHAR string21[64];
TCHAR string22[64];
TCHAR string23[64];
TCHAR string24[64];
TCHAR string25[64];
TCHAR string26[64];
TCHAR string27[64];
TCHAR string28[64];
TCHAR string29[64];
TCHAR string30[64];
TCHAR string31[64];
TCHAR string32[64];
TCHAR string33[64];
TCHAR string34[64];
TCHAR string35[64];
TCHAR string36[64];
TCHAR string37[64];
TCHAR string38[64];
TCHAR string39[64];
TCHAR string40[64];
TCHAR string41[64];
TCHAR string42[64];
TCHAR string43[64];
TCHAR string44[64];
TCHAR string45[64];
TCHAR string46[64];
TCHAR string47[64];
TCHAR string48[64];
TCHAR string49[64];
TCHAR string50[64];
TCHAR string51[64];
TCHAR string52[64];
TCHAR string53[64];
TCHAR string54[64];
TCHAR string55[64];
TCHAR string56[64];
TCHAR string57[64];
TCHAR string58[64];
TCHAR string59[64];
TCHAR string60[64];
TCHAR string61[64];
TCHAR string62[64];
TCHAR string63[64];
TCHAR string64[64];
TCHAR string65[64];
TCHAR string66[64];
TCHAR string67[64];
TCHAR string68[64];
TCHAR string69[64];
TCHAR string70[64];
TCHAR string71[64];
TCHAR string72[64];
TCHAR string73[64];
TCHAR string74[64];
TCHAR string75[64];
TCHAR string76[64];
TCHAR string77[64];
TCHAR string78[64];
TCHAR string79[64];
TCHAR string80[64];
TCHAR string81[64];
TCHAR string82[64];
TCHAR string83[64];
TCHAR string84[64];
TCHAR string85[64];
TCHAR string86[64];
TCHAR string87[64];
TCHAR string88[64];
TCHAR string89[64];
TCHAR string90[64];
TCHAR string91[64];
TCHAR string92[64];
TCHAR string93[64];
TCHAR string94[64];
TCHAR string95[64];
TCHAR string96[64];
TCHAR string97[64];
TCHAR string98[64];
TCHAR string99[64];
TCHAR string100[64];



TCHAR szBuffer[256];

//キャラ、枠画像
DWORD charac = GetPrivateProfileString(_T("Graphic"), _T("Character"), _T("../pictures/yuyuko.png"), chara, sizeof(chara) / sizeof(TCHAR), _T("../config.ini"));
DWORD messwind = GetPrivateProfileString(_T("Graphic"), _T("MessageWindow"), _T("../pictures/yuyuko.png"), mswindow, sizeof(mswindow) / sizeof(TCHAR), _T("..\\config.ini"));

DWORD st1 = GetPrivateProfileString(_T("Message"), _T("M1"), _T(""), string1, sizeof(string1) / sizeof(TCHAR), _T("../config.ini"));
DWORD st2 = GetPrivateProfileString(_T("Message"), _T("M2"), _T(""), string2, sizeof(string2) / sizeof(TCHAR), _T("../config.ini"));
DWORD st3 = GetPrivateProfileString(_T("Message"), _T("M3"), _T(""), string3, sizeof(string3) / sizeof(TCHAR), _T("../config.ini"));
DWORD st4 = GetPrivateProfileString(_T("Message"), _T("M4"), _T(""), string4, sizeof(string4) / sizeof(TCHAR), _T("../config.ini"));
DWORD st5 = GetPrivateProfileString(_T("Message"), _T("M5"), _T(""), string5, sizeof(string5) / sizeof(TCHAR), _T("../config.ini"));
DWORD st6 = GetPrivateProfileString(_T("Message"), _T("M6"), _T(""), string6, sizeof(string6) / sizeof(TCHAR), _T("../config.ini"));
DWORD st7 = GetPrivateProfileString(_T("Message"), _T("M7"), _T(""), string7, sizeof(string7) / sizeof(TCHAR), _T("../config.ini"));
DWORD st8 = GetPrivateProfileString(_T("Message"), _T("M8"), _T(""), string8, sizeof(string8) / sizeof(TCHAR), _T("../config.ini"));
DWORD st9= GetPrivateProfileString(_T("Message"), _T("M9"), _T(""), string9, sizeof(string9) / sizeof(TCHAR), _T("../config.ini"));
DWORD st10 = GetPrivateProfileString(_T("Message"), _T("M10"), _T(""), string10, sizeof(string10) / sizeof(TCHAR), _T("../config.ini"));
DWORD st11 = GetPrivateProfileString(_T("Message"), _T("M11"), _T(""), string11, sizeof(string11) / sizeof(TCHAR), _T("../config.ini"));
DWORD st12 = GetPrivateProfileString(_T("Message"), _T("M12"), _T(""), string12, sizeof(string12) / sizeof(TCHAR), _T("../config.ini"));
DWORD st13 = GetPrivateProfileString(_T("Message"), _T("M13"), _T(""), string13, sizeof(string13) / sizeof(TCHAR), _T("../config.ini"));
DWORD st14 = GetPrivateProfileString(_T("Message"), _T("M14"), _T(""), string14, sizeof(string14) / sizeof(TCHAR), _T("../config.ini"));
DWORD st15 = GetPrivateProfileString(_T("Message"), _T("M15"), _T(""), string15, sizeof(string15) / sizeof(TCHAR), _T("../config.ini"));
DWORD st16 = GetPrivateProfileString(_T("Message"), _T("M16"), _T(""), string16, sizeof(string16) / sizeof(TCHAR), _T("../config.ini"));
DWORD st17 = GetPrivateProfileString(_T("Message"), _T("M17"), _T(""), string17, sizeof(string17) / sizeof(TCHAR), _T("../config.ini"));
DWORD st18 = GetPrivateProfileString(_T("Message"), _T("M18"), _T(""), string18, sizeof(string18) / sizeof(TCHAR), _T("../config.ini"));
DWORD st19 = GetPrivateProfileString(_T("Message"), _T("M19"), _T(""), string19, sizeof(string19) / sizeof(TCHAR), _T("../config.ini"));
DWORD st20 = GetPrivateProfileString(_T("Message"), _T("M20"), _T(""), string20, sizeof(string20) / sizeof(TCHAR), _T("../config.ini"));
DWORD st21 = GetPrivateProfileString(_T("Message"), _T("M21"), _T(""), string11, sizeof(string11) / sizeof(TCHAR), _T("../config.ini"));
DWORD st22 = GetPrivateProfileString(_T("Message"), _T("M22"), _T(""), string12, sizeof(string12) / sizeof(TCHAR), _T("../config.ini"));
DWORD st23 = GetPrivateProfileString(_T("Message"), _T("M23"), _T(""), string13, sizeof(string13) / sizeof(TCHAR), _T("../config.ini"));
DWORD st24 = GetPrivateProfileString(_T("Message"), _T("M24"), _T(""), string14, sizeof(string14) / sizeof(TCHAR), _T("../config.ini"));
DWORD st25 = GetPrivateProfileString(_T("Message"), _T("M25"), _T(""), string15, sizeof(string15) / sizeof(TCHAR), _T("../config.ini"));
DWORD st26 = GetPrivateProfileString(_T("Message"), _T("M26"), _T(""), string16, sizeof(string16) / sizeof(TCHAR), _T("../config.ini"));
DWORD st27 = GetPrivateProfileString(_T("Message"), _T("M27"), _T(""), string17, sizeof(string17) / sizeof(TCHAR), _T("../config.ini"));
DWORD st28 = GetPrivateProfileString(_T("Message"), _T("M28"), _T(""), string18, sizeof(string18) / sizeof(TCHAR), _T("../config.ini"));
DWORD st29 = GetPrivateProfileString(_T("Message"), _T("M29"), _T(""), string19, sizeof(string19) / sizeof(TCHAR), _T("../config.ini"));
DWORD st30 = GetPrivateProfileString(_T("Message"), _T("M30"), _T(""), string20, sizeof(string20) / sizeof(TCHAR), _T("../config.ini"));
DWORD st31 = GetPrivateProfileString(_T("Message"), _T("M31"), _T(""), string31, sizeof(string31) / sizeof(TCHAR), _T("../config.ini"));
DWORD st32 = GetPrivateProfileString(_T("Message"), _T("M32"), _T(""), string32, sizeof(string32) / sizeof(TCHAR), _T("../config.ini"));
DWORD st33 = GetPrivateProfileString(_T("Message"), _T("M33"), _T(""), string33, sizeof(string33) / sizeof(TCHAR), _T("../config.ini"));
DWORD st34 = GetPrivateProfileString(_T("Message"), _T("M34"), _T(""), string34, sizeof(string34) / sizeof(TCHAR), _T("../config.ini"));
DWORD st35 = GetPrivateProfileString(_T("Message"), _T("M35"), _T(""), string35, sizeof(string35) / sizeof(TCHAR), _T("../config.ini"));
DWORD st36 = GetPrivateProfileString(_T("Message"), _T("M36"), _T(""), string36, sizeof(string36) / sizeof(TCHAR), _T("../config.ini"));
DWORD st37 = GetPrivateProfileString(_T("Message"), _T("M37"), _T(""), string37, sizeof(string37) / sizeof(TCHAR), _T("../config.ini"));
DWORD st38 = GetPrivateProfileString(_T("Message"), _T("M38"), _T(""), string38, sizeof(string38) / sizeof(TCHAR), _T("../config.ini"));
DWORD st39 = GetPrivateProfileString(_T("Message"), _T("M39"), _T(""), string39, sizeof(string39) / sizeof(TCHAR), _T("../config.ini"));
DWORD st40 = GetPrivateProfileString(_T("Message"), _T("M40"), _T(""), string40, sizeof(string40) / sizeof(TCHAR), _T("../config.ini"));
DWORD st41 = GetPrivateProfileString(_T("Message"), _T("M41"), _T(""), string41, sizeof(string41) / sizeof(TCHAR), _T("../config.ini"));
DWORD st42 = GetPrivateProfileString(_T("Message"), _T("M42"), _T(""), string42, sizeof(string42) / sizeof(TCHAR), _T("../config.ini"));
DWORD st43 = GetPrivateProfileString(_T("Message"), _T("M43"), _T(""), string43, sizeof(string43) / sizeof(TCHAR), _T("../config.ini"));
DWORD st44 = GetPrivateProfileString(_T("Message"), _T("M44"), _T(""), string44, sizeof(string44) / sizeof(TCHAR), _T("../config.ini"));
DWORD st45 = GetPrivateProfileString(_T("Message"), _T("M45"), _T(""), string45, sizeof(string45) / sizeof(TCHAR), _T("../config.ini"));
DWORD st46 = GetPrivateProfileString(_T("Message"), _T("M46"), _T(""), string46, sizeof(string46) / sizeof(TCHAR), _T("../config.ini"));
DWORD st47 = GetPrivateProfileString(_T("Message"), _T("M47"), _T(""), string47, sizeof(string47) / sizeof(TCHAR), _T("../config.ini"));
DWORD st48 = GetPrivateProfileString(_T("Message"), _T("M48"), _T(""), string48, sizeof(string48) / sizeof(TCHAR), _T("../config.ini"));
DWORD st49 = GetPrivateProfileString(_T("Message"), _T("M49"), _T(""), string49, sizeof(string49) / sizeof(TCHAR), _T("../config.ini"));
DWORD st50 = GetPrivateProfileString(_T("Message"), _T("M50"), _T(""), string50, sizeof(string50) / sizeof(TCHAR), _T("../config.ini"));
DWORD st51 = GetPrivateProfileString(_T("Message"), _T("M51"), _T(""), string51, sizeof(string51) / sizeof(TCHAR), _T("../config.ini"));
DWORD st52 = GetPrivateProfileString(_T("Message"), _T("M52"), _T(""), string52, sizeof(string52) / sizeof(TCHAR), _T("../config.ini"));
DWORD st53 = GetPrivateProfileString(_T("Message"), _T("M53"), _T(""), string53, sizeof(string53) / sizeof(TCHAR), _T("../config.ini"));
DWORD st54 = GetPrivateProfileString(_T("Message"), _T("M54"), _T(""), string54, sizeof(string54) / sizeof(TCHAR), _T("../config.ini"));
DWORD st55 = GetPrivateProfileString(_T("Message"), _T("M55"), _T(""), string55, sizeof(string55) / sizeof(TCHAR), _T("../config.ini"));
DWORD st56 = GetPrivateProfileString(_T("Message"), _T("M56"), _T(""), string56, sizeof(string56) / sizeof(TCHAR), _T("../config.ini"));
DWORD st57 = GetPrivateProfileString(_T("Message"), _T("M57"), _T(""), string57, sizeof(string57) / sizeof(TCHAR), _T("../config.ini"));
DWORD st58 = GetPrivateProfileString(_T("Message"), _T("M58"), _T(""), string58, sizeof(string58) / sizeof(TCHAR), _T("../config.ini"));
DWORD st59 = GetPrivateProfileString(_T("Message"), _T("M59"), _T(""), string59, sizeof(string59) / sizeof(TCHAR), _T("../config.ini"));
DWORD st60 = GetPrivateProfileString(_T("Message"), _T("M60"), _T(""), string60, sizeof(string60) / sizeof(TCHAR), _T("../config.ini"));
DWORD st61 = GetPrivateProfileString(_T("Message"), _T("M61"), _T(""), string61, sizeof(string61) / sizeof(TCHAR), _T("../config.ini"));
DWORD st62 = GetPrivateProfileString(_T("Message"), _T("M62"), _T(""), string62, sizeof(string62) / sizeof(TCHAR), _T("../config.ini"));
DWORD st63 = GetPrivateProfileString(_T("Message"), _T("M63"), _T(""), string63, sizeof(string63) / sizeof(TCHAR), _T("../config.ini"));
DWORD st64 = GetPrivateProfileString(_T("Message"), _T("M64"), _T(""), string64, sizeof(string64) / sizeof(TCHAR), _T("../config.ini"));
DWORD st65 = GetPrivateProfileString(_T("Message"), _T("M65"), _T(""), string65, sizeof(string65) / sizeof(TCHAR), _T("../config.ini"));
DWORD st66 = GetPrivateProfileString(_T("Message"), _T("M66"), _T(""), string66, sizeof(string66) / sizeof(TCHAR), _T("../config.ini"));
DWORD st67 = GetPrivateProfileString(_T("Message"), _T("M67"), _T(""), string67, sizeof(string67) / sizeof(TCHAR), _T("../config.ini"));
DWORD st68 = GetPrivateProfileString(_T("Message"), _T("M68"), _T(""), string68, sizeof(string68) / sizeof(TCHAR), _T("../config.ini"));
DWORD st69 = GetPrivateProfileString(_T("Message"), _T("M69"), _T(""), string69, sizeof(string69) / sizeof(TCHAR), _T("../config.ini"));
DWORD st70 = GetPrivateProfileString(_T("Message"), _T("M70"), _T(""), string70, sizeof(string70) / sizeof(TCHAR), _T("../config.ini"));
DWORD st71 = GetPrivateProfileString(_T("Message"), _T("M71"), _T(""), string71, sizeof(string71) / sizeof(TCHAR), _T("../config.ini"));
DWORD st72 = GetPrivateProfileString(_T("Message"), _T("M72"), _T(""), string72, sizeof(string72) / sizeof(TCHAR), _T("../config.ini"));
DWORD st73 = GetPrivateProfileString(_T("Message"), _T("M73"), _T(""), string73, sizeof(string73) / sizeof(TCHAR), _T("../config.ini"));
DWORD st74 = GetPrivateProfileString(_T("Message"), _T("M74"), _T(""), string74, sizeof(string74) / sizeof(TCHAR), _T("../config.ini"));
DWORD st75 = GetPrivateProfileString(_T("Message"), _T("M75"), _T(""), string75, sizeof(string75) / sizeof(TCHAR), _T("../config.ini"));
DWORD st76 = GetPrivateProfileString(_T("Message"), _T("M76"), _T(""), string76, sizeof(string76) / sizeof(TCHAR), _T("../config.ini"));
DWORD st77 = GetPrivateProfileString(_T("Message"), _T("M77"), _T(""), string77, sizeof(string77) / sizeof(TCHAR), _T("../config.ini"));
DWORD st78 = GetPrivateProfileString(_T("Message"), _T("M87"), _T(""), string78, sizeof(string78) / sizeof(TCHAR), _T("../config.ini"));
DWORD st79 = GetPrivateProfileString(_T("Message"), _T("M97"), _T(""), string79, sizeof(string79) / sizeof(TCHAR), _T("../config.ini"));
DWORD st80 = GetPrivateProfileString(_T("Message"), _T("M80"), _T(""), string80, sizeof(string80) / sizeof(TCHAR), _T("../config.ini"));
DWORD st81 = GetPrivateProfileString(_T("Message"), _T("M81"), _T(""), string81, sizeof(string81) / sizeof(TCHAR), _T("../config.ini"));
DWORD st82 = GetPrivateProfileString(_T("Message"), _T("M82"), _T(""), string82, sizeof(string82) / sizeof(TCHAR), _T("../config.ini"));
DWORD st83 = GetPrivateProfileString(_T("Message"), _T("M83"), _T(""), string83, sizeof(string83) / sizeof(TCHAR), _T("../config.ini"));
DWORD st84 = GetPrivateProfileString(_T("Message"), _T("M84"), _T(""), string84, sizeof(string84) / sizeof(TCHAR), _T("../config.ini"));
DWORD st85 = GetPrivateProfileString(_T("Message"), _T("M85"), _T(""), string85, sizeof(string85) / sizeof(TCHAR), _T("../config.ini"));
DWORD st86 = GetPrivateProfileString(_T("Message"), _T("M86"), _T(""), string86, sizeof(string86) / sizeof(TCHAR), _T("../config.ini"));
DWORD st87 = GetPrivateProfileString(_T("Message"), _T("M87"), _T(""), string87, sizeof(string87) / sizeof(TCHAR), _T("../config.ini"));
DWORD st88 = GetPrivateProfileString(_T("Message"), _T("M88"), _T(""), string88, sizeof(string88) / sizeof(TCHAR), _T("../config.ini"));
DWORD st89 = GetPrivateProfileString(_T("Message"), _T("M89"), _T(""), string89, sizeof(string89) / sizeof(TCHAR), _T("../config.ini"));
DWORD st90 = GetPrivateProfileString(_T("Message"), _T("M90"), _T(""), string90, sizeof(string90) / sizeof(TCHAR), _T("../config.ini"));
DWORD st91 = GetPrivateProfileString(_T("Message"), _T("M91"), _T(""), string91, sizeof(string91) / sizeof(TCHAR), _T("../config.ini"));
DWORD st92 = GetPrivateProfileString(_T("Message"), _T("M92"), _T(""), string92, sizeof(string92) / sizeof(TCHAR), _T("../config.ini"));
DWORD st93 = GetPrivateProfileString(_T("Message"), _T("M93"), _T(""), string93, sizeof(string93) / sizeof(TCHAR), _T("../config.ini"));
DWORD st94 = GetPrivateProfileString(_T("Message"), _T("M94"), _T(""), string94, sizeof(string94) / sizeof(TCHAR), _T("../config.ini"));
DWORD st95 = GetPrivateProfileString(_T("Message"), _T("M95"), _T(""), string95, sizeof(string95) / sizeof(TCHAR), _T("../config.ini"));
DWORD st96 = GetPrivateProfileString(_T("Message"), _T("M96"), _T(""), string96, sizeof(string96) / sizeof(TCHAR), _T("../config.ini"));
DWORD st97 = GetPrivateProfileString(_T("Message"), _T("M97"), _T(""), string97, sizeof(string97) / sizeof(TCHAR), _T("../config.ini"));
DWORD st98 = GetPrivateProfileString(_T("Message"), _T("M98"), _T(""), string98, sizeof(string98) / sizeof(TCHAR), _T("../config.ini"));
DWORD st99 = GetPrivateProfileString(_T("Message"), _T("M99"), _T(""), string99, sizeof(string99) / sizeof(TCHAR), _T("../config.ini"));
DWORD st100 = GetPrivateProfileString(_T("Message"), _T("M100"), _T(""), string100, sizeof(string100) / sizeof(TCHAR), _T("../config.ini"));


//月
int string1_M = GetPrivateProfileIntA(_T("Month"), _T("M3"), 0, _T("../config.ini"));
int string2_M = GetPrivateProfileIntA(_T("Month"), _T("M2"), 0, _T("../config.ini"));
int string3_M = GetPrivateProfileIntA(_T("Month"), _T("M3"), 0, _T("../config.ini"));
int string4_M = GetPrivateProfileIntA(_T("Month"), _T("M4"), 0, _T("../config.ini"));
int string5_M = GetPrivateProfileIntA(_T("Month"), _T("M5"), 0, _T("../config.ini"));
int string6_M = GetPrivateProfileIntA(_T("Month"), _T("M6"), 0, _T("../config.ini"));
int string7_M = GetPrivateProfileIntA(_T("Month"), _T("M7"), 0, _T("../config.ini"));
int string8_M = GetPrivateProfileIntA(_T("Month"), _T("M8"), 0, _T("../config.ini"));
int string9_M = GetPrivateProfileIntA(_T("Month"), _T("M9"), 0, _T("../config.ini"));
int string10_M = GetPrivateProfileIntA(_T("Month"), _T("M10"), 0, _T("../config.ini"));
int string11_M = GetPrivateProfileIntA(_T("Month"), _T("M11"), 0, _T("../config.ini"));
int string12_M = GetPrivateProfileIntA(_T("Month"), _T("M12"), 0, _T("../config.ini"));
int string13_M = GetPrivateProfileIntA(_T("Month"), _T("M13"), 0, _T("../config.ini"));
int string14_M = GetPrivateProfileIntA(_T("Month"), _T("M14"), 0, _T("../config.ini"));
int string15_M = GetPrivateProfileIntA(_T("Month"), _T("M15"), 0, _T("../config.ini"));
int string16_M = GetPrivateProfileIntA(_T("Month"), _T("M16"), 0, _T("../config.ini"));
int string17_M = GetPrivateProfileIntA(_T("Month"), _T("M17"), 0, _T("../config.ini"));
int string18_M = GetPrivateProfileIntA(_T("Month"), _T("M18"), 0, _T("../config.ini"));
int string19_M = GetPrivateProfileIntA(_T("Month"), _T("M19"), 0, _T("../config.ini"));
int string20_M = GetPrivateProfileIntA(_T("Month"), _T("M20"), 0, _T("../config.ini"));
int string21_M = GetPrivateProfileIntA(_T("Month"), _T("M23"), 0, _T("../config.ini"));
int string22_M = GetPrivateProfileIntA(_T("Month"), _T("M22"), 0, _T("../config.ini"));
int string23_M = GetPrivateProfileIntA(_T("Month"), _T("M23"), 0, _T("../config.ini"));
int string24_M = GetPrivateProfileIntA(_T("Month"), _T("M24"), 0, _T("../config.ini"));
int string25_M = GetPrivateProfileIntA(_T("Month"), _T("M25"), 0, _T("../config.ini"));
int string26_M = GetPrivateProfileIntA(_T("Month"), _T("M26"), 0, _T("../config.ini"));
int string27_M = GetPrivateProfileIntA(_T("Month"), _T("M27"), 0, _T("../config.ini"));
int string28_M = GetPrivateProfileIntA(_T("Month"), _T("M28"), 0, _T("../config.ini"));
int string29_M = GetPrivateProfileIntA(_T("Month"), _T("M29"), 0, _T("../config.ini"));
int string30_M = GetPrivateProfileIntA(_T("Month"), _T("M30"), 0, _T("../config.ini"));
int string31_M = GetPrivateProfileIntA(_T("Month"), _T("M31"), 0, _T("../config.ini"));
int string32_M = GetPrivateProfileIntA(_T("Month"), _T("M32"), 0, _T("../config.ini"));
int string33_M = GetPrivateProfileIntA(_T("Month"), _T("M33"), 0, _T("../config.ini"));
int string34_M = GetPrivateProfileIntA(_T("Month"), _T("M34"), 0, _T("../config.ini"));
int string35_M = GetPrivateProfileIntA(_T("Month"), _T("M35"), 0, _T("../config.ini"));
int string36_M = GetPrivateProfileIntA(_T("Month"), _T("M36"), 0, _T("../config.ini"));
int string37_M = GetPrivateProfileIntA(_T("Month"), _T("M37"), 0, _T("../config.ini"));
int string38_M = GetPrivateProfileIntA(_T("Month"), _T("M38"), 0, _T("../config.ini"));
int string39_M = GetPrivateProfileIntA(_T("Month"), _T("M39"), 0, _T("../config.ini"));
int string40_M = GetPrivateProfileIntA(_T("Month"), _T("M40"), 0, _T("../config.ini"));
int string41_M = GetPrivateProfileIntA(_T("Month"), _T("M41"), 0, _T("../config.ini"));
int string42_M = GetPrivateProfileIntA(_T("Month"), _T("M42"), 0, _T("../config.ini"));
int string43_M = GetPrivateProfileIntA(_T("Month"), _T("M43"), 0, _T("../config.ini"));
int string44_M = GetPrivateProfileIntA(_T("Month"), _T("M44"), 0, _T("../config.ini"));
int string45_M = GetPrivateProfileIntA(_T("Month"), _T("M45"), 0, _T("../config.ini"));
int string46_M = GetPrivateProfileIntA(_T("Month"), _T("M46"), 0, _T("../config.ini"));
int string47_M = GetPrivateProfileIntA(_T("Month"), _T("M47"), 0, _T("../config.ini"));
int string48_M = GetPrivateProfileIntA(_T("Month"), _T("M48"), 0, _T("../config.ini"));
int string49_M = GetPrivateProfileIntA(_T("Month"), _T("M49"), 0, _T("../config.ini"));
int string50_M = GetPrivateProfileIntA(_T("Month"), _T("M50"), 0, _T("../config.ini"));
int string51_M = GetPrivateProfileIntA(_T("Month"), _T("M51"), 0, _T("../config.ini"));
int string52_M = GetPrivateProfileIntA(_T("Month"), _T("M52"), 0, _T("../config.ini"));
int string53_M = GetPrivateProfileIntA(_T("Month"), _T("M53"), 0, _T("../config.ini"));
int string54_M = GetPrivateProfileIntA(_T("Month"), _T("M54"), 0, _T("../config.ini"));
int string55_M = GetPrivateProfileIntA(_T("Month"), _T("M55"), 0, _T("../config.ini"));
int string56_M = GetPrivateProfileIntA(_T("Month"), _T("M56"), 0, _T("../config.ini"));
int string57_M = GetPrivateProfileIntA(_T("Month"), _T("M57"), 0, _T("../config.ini"));
int string58_M = GetPrivateProfileIntA(_T("Month"), _T("M58"), 0, _T("../config.ini"));
int string59_M = GetPrivateProfileIntA(_T("Month"), _T("M59"), 0, _T("../config.ini"));
int string60_M = GetPrivateProfileIntA(_T("Month"), _T("M60"), 0, _T("../config.ini"));
int string61_M = GetPrivateProfileIntA(_T("Month"), _T("M61"), 0, _T("../config.ini"));
int string62_M = GetPrivateProfileIntA(_T("Month"), _T("M62"), 0, _T("../config.ini"));
int string63_M = GetPrivateProfileIntA(_T("Month"), _T("M63"), 0, _T("../config.ini"));
int string64_M = GetPrivateProfileIntA(_T("Month"), _T("M64"), 0, _T("../config.ini"));
int string65_M = GetPrivateProfileIntA(_T("Month"), _T("M65"), 0, _T("../config.ini"));
int string66_M = GetPrivateProfileIntA(_T("Month"), _T("M66"), 0, _T("../config.ini"));
int string67_M = GetPrivateProfileIntA(_T("Month"), _T("M67"), 0, _T("../config.ini"));
int string68_M = GetPrivateProfileIntA(_T("Month"), _T("M68"), 0, _T("../config.ini"));
int string69_M = GetPrivateProfileIntA(_T("Month"), _T("M69"), 0, _T("../config.ini"));
int string70_M = GetPrivateProfileIntA(_T("Month"), _T("M70"), 0, _T("../config.ini"));
int string71_M = GetPrivateProfileIntA(_T("Month"), _T("M71"), 0, _T("../config.ini"));
int string72_M = GetPrivateProfileIntA(_T("Month"), _T("M72"), 0, _T("../config.ini"));
int string73_M = GetPrivateProfileIntA(_T("Month"), _T("M73"), 0, _T("../config.ini"));
int string74_M = GetPrivateProfileIntA(_T("Month"), _T("M74"), 0, _T("../config.ini"));
int string75_M = GetPrivateProfileIntA(_T("Month"), _T("M75"), 0, _T("../config.ini"));
int string76_M = GetPrivateProfileIntA(_T("Month"), _T("M76"), 0, _T("../config.ini"));
int string77_M = GetPrivateProfileIntA(_T("Month"), _T("M77"), 0, _T("../config.ini"));
int string78_M = GetPrivateProfileIntA(_T("Month"), _T("M78"), 0, _T("../config.ini"));
int string79_M = GetPrivateProfileIntA(_T("Month"), _T("M79"), 0, _T("../config.ini"));
int string80_M = GetPrivateProfileIntA(_T("Month"), _T("M80"), 0, _T("../config.ini"));
int string81_M = GetPrivateProfileIntA(_T("Month"), _T("M81"), 0, _T("../config.ini"));
int string82_M = GetPrivateProfileIntA(_T("Month"), _T("M82"), 0, _T("../config.ini"));
int string83_M = GetPrivateProfileIntA(_T("Month"), _T("M83"), 0, _T("../config.ini"));
int string84_M = GetPrivateProfileIntA(_T("Month"), _T("M84"), 0, _T("../config.ini"));
int string85_M = GetPrivateProfileIntA(_T("Month"), _T("M85"), 0, _T("../config.ini"));
int string86_M = GetPrivateProfileIntA(_T("Month"), _T("M86"), 0, _T("../config.ini"));
int string87_M = GetPrivateProfileIntA(_T("Month"), _T("M87"), 0, _T("../config.ini"));
int string88_M = GetPrivateProfileIntA(_T("Month"), _T("M88"), 0, _T("../config.ini"));
int string89_M = GetPrivateProfileIntA(_T("Month"), _T("M89"), 0, _T("../config.ini"));
int string90_M = GetPrivateProfileIntA(_T("Month"), _T("M90"), 0, _T("../config.ini"));
int string91_M = GetPrivateProfileIntA(_T("Month"), _T("M91"), 0, _T("../config.ini"));
int string92_M = GetPrivateProfileIntA(_T("Month"), _T("M92"), 0, _T("../config.ini"));
int string93_M = GetPrivateProfileIntA(_T("Month"), _T("M93"), 0, _T("../config.ini"));
int string94_M = GetPrivateProfileIntA(_T("Month"), _T("M94"), 0, _T("../config.ini"));
int string95_M = GetPrivateProfileIntA(_T("Month"), _T("M95"), 0, _T("../config.ini"));
int string96_M = GetPrivateProfileIntA(_T("Month"), _T("M96"), 0, _T("../config.ini"));
int string97_M = GetPrivateProfileIntA(_T("Month"), _T("M97"), 0, _T("../config.ini"));
int string98_M = GetPrivateProfileIntA(_T("Month"), _T("M98"), 0, _T("../config.ini"));
int string99_M = GetPrivateProfileIntA(_T("Month"), _T("M99"), 0, _T("../config.ini"));
int string100_M = GetPrivateProfileIntA(_T("Month"), _T("M100"), 0, _T("../config.ini"));

//座標
int CharaX = GetPrivateProfileIntA(_T("Position"), _T("CharaX"), 280, _T("../config.ini"));
int CharaY = GetPrivateProfileIntA(_T("Position"), _T("CharaY"), 0, _T("../config.ini"));
int MessageWindowX = GetPrivateProfileIntA(_T("Position"), _T("MessageWindowX"), 0, _T("../config.ini"));
int MessageWindowY = GetPrivateProfileIntA(_T("Position"), _T("MessageWindowY"), 0, _T("../config.ini"));
int MessageX = GetPrivateProfileIntA(_T("Position"), _T("MessageX"), 0, _T("../config.ini"));
int MessageY = GetPrivateProfileIntA(_T("Position"), _T("MessageX"), 0, _T("../config.ini"));
